"use client";

import Head from "next/head";
import { useState } from "react";

export default function AboutMe() {
  const [showMore, setShowMore] = useState(false);

  return (
    <div className="bg-white min-h-screen flex items-center justify-center p-4 dark:bg-gray-800 dark:text-white">
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto text-center">
        <h1 className="text-3xl font-bold mb-4">About Me</h1>
      
        <div className="flex flex-col lg:flex-row justify-center items-center space-y-6 lg:space-y-0 lg:space-x-6">
          {/* Profile Image Section */}
          <div className="w-[80%] sm:w-[50%] lg:w-[30%] h-80 relative rounded-full overflow-hidden border-8 border-gradient-to-r from-teal-400 to-lime-500 bg-gradient-to-r from-red-500 via-yellow-500 to-blue-500 shadow-xl">
            <div
              className="absolute inset-0 bg-cover bg-center backdrop-blur-sm"
              style={{ backgroundImage: "url('/masri1.jpg')" }}
            />
            <div className="w-full h-full bg-[rgb(202,199,25)] opacity-0" />
          </div>

          {/* About Text Section */}
          <div className="w-[80%] sm:w-[70%] lg:w-[50%] text-left">
            <p className="text-lg mb-4">
              Results-driven software engineer with 2+ years of experience in mobile app development, web app development, AI integration, and cybersecurity. Successfully completed 50+ projects, including 10+ large-scale applications, with international and local experience in remote and onsite roles.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4 mt-4">
              <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full sm:w-auto">
                Let's Connect
              </button>
              <button
                onClick={() => console.log("click")}
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full sm:w-auto"
              >
                Resume
              </button>
            </div>
          
          </div>
        </div>
      </main>
    </div>
  );
}
