"use client"; // Add this at the top to mark this as a client-side component

import Head from 'next/head';
import { useState } from 'react';

export default function AboutMe() {
  const [showMore, setShowMore] = useState(false);

  return (
    <div className="bg-white min-h-screen flex items-center justify-center p-4">
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto text-center">
        <h1 className="text-3xl font-bold mb-4">About Me</h1>
        <p className="text-lg mb-4">Who I am</p>

        <div className="flex flex-col lg:flex-row justify-center items-center space-y-6 lg:space-y-0 lg:space-x-6">
          {/* Profile Image - takes 30% of the width on large screens */}
          <div className="w-[80%] sm:w-[50%] lg:w-[30%] h-80 relative rounded-full overflow-hidden">
            <div
              className="absolute inset-0 bg-cover bg-center backdrop-blur-sm"
              style={{ backgroundImage: "url('/masri1.jpg')" }} // Set background image
            />
            <div className="w-full h-full bg-[rgb(151,150,148)] opacity-0" /> {/* This adds the semi-transparent background */}
          </div>

          {/* Text - takes 80% of the width on small screens, 50% on large screens */}
          <div className="w-[80%] sm:w-[70%] lg:w-[50%] text-left">
            <p className="text-lg mb-4">
              Passionate software engineer with expertise in MERN stack and Python (Flask, MySQL).
              Skilled in creating user-friendly web applications, SQL databases, and chatbot
              development. Proficient in automation (Selenium) and enjoys bringing projects to life with
              animation (Pygame). Dedicated to pushing boundaries and transforming ideas into reality.
              Let's connect and create something extraordinary!
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4 mt-4">
              {/* Buttons - Centered and responsive */}
              <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full sm:w-auto">
                Let's Connect
              </button>
              <button
                onClick={() => console.log('click')}
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full sm:w-auto"
              >
                Resume
              </button>
            </div>
            {showMore && (
              <p className="text-lg mt-2">
                I enjoy learning new technologies, building side projects, and collaborating with others to
                bring innovative ideas to life. Let's work together to build amazing things!
              </p>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
